name       : vkd3d
version    : 1.0
release    : 1
source     :
    - https://dl.winehq.org/vkd3d/source/vkd3d-1.0.tar.xz : 439d9eb22125b89f326e4055908e2e93b93b55c5bb2e47b1462caf2ad5c1df17
license    : LGPL-2.1-or-later
component  : programming.library
summary    : vkd3d 3D Graphics Library
description: |
    Vkd3d is a 3D graphics library built on top of Vulkan. It has an API very similar, but not identical, to Direct3D 12.
emul32     : yes
builddeps  :
    - pkgconfig32(vulkan)
    - pkgconfig32(xcb)
    - pkgconfig32(xcb-icccm)
    - pkgconfig32(xcb-keysyms)
    - pkgconfig32(xcb-util)
    - pkgconfig32(x11)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
