name       : vkd3d
version    : 1.1
release    : 3
source     :
    - https://dl.winehq.org/vkd3d/source/vkd3d-1.1.tar.xz : 495adc61cc80c65d54b2f5b52092ea05d3797cc2c17a610f0fc98457d2f56ab6
license    : LGPL-2.1-or-later
component  : programming.library
summary    : vkd3d 3D Graphics Library
description: |
    Vkd3d is a 3D graphics library built on top of Vulkan. It has an API very similar, but not identical, to Direct3D 12.
emul32     : yes
builddeps  :
    - pkgconfig32(vulkan)
    - pkgconfig32(xcb)
    - pkgconfig32(xcb-icccm)
    - pkgconfig32(xcb-keysyms)
    - pkgconfig32(xcb-util)
    - pkgconfig32(x11)
    - spirv-headers
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
