name       : vkd3d
version    : '1.2'
release    : 6
source     :
    - https://dl.winehq.org/vkd3d/source/vkd3d-1.2.tar.xz : b04b030fcbf0f2dacc933c76c74b449bffef1fc1a18d50254ef1ad3e380df96b
license    : LGPL-2.1-or-later
component  : programming.library
summary    : vkd3d 3D Graphics Library
description: |
    Vkd3d is a 3D graphics library built on top of Vulkan. It has an API very similar, but not identical, to Direct3D 12.
emul32     : yes
builddeps  :
    - pkgconfig32(vulkan)
    - pkgconfig32(xcb)
    - pkgconfig32(xcb-icccm)
    - pkgconfig32(xcb-keysyms)
    - pkgconfig32(xcb-util)
    - pkgconfig32(x11)
    - spirv-headers
    - vulkan-headers
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
